name: my_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.3
  # splashscreen: ^1.3.5
  # random_avatar: ^0.0.7
  url_launcher: ^6.1.5
  # dot_navigation_bar: ^1.0.1+4
  sqflite: ^2.0.3
  # flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.1+1
  # smooth_star_rating: ^1.1.1
  # the smooth star packge doesn't support null safty
  # smooth_star_rating: 1.0.4+2
  # persistent_bottom_nav_bar: ^4.0.2
  # flutter_inner_drawer: ^1.0.0+1
  # simple_animations: ^4.2.0
  get: ^4.6.5
  # iconsax: ^0.0.8
  # flutter_remix: ^0.0.1
  intro_slider: ^3.0.9
  # flutter_launcher_icons_maker: "^0.10.1"
  # animated_theme_switcher: ^2.0.6
  # day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.0.15
  # get_storage:
  convex_bottom_bar: ^3.0.0
  json_serializable: ^6.3.1



dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mainIcon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/mainIcon.png
  ios: true
  android_gravity: center
  #image_dark: assets/android12splash-invert.png
  color_dark: "#282828"

flutter:

  uses-material-design: true

  assets:
    - assets/foods/beef meat/
    - assets/foods/chinese food/
    - assets/foods/juice/
    - assets/foods/noodles/
    - assets/foods/pasta/
    - assets/foods/salad/
    - assets/foods/soda/
    - assets/icons/
    - assets/images/
    - assets/svgicons/
    - assets/foods/beef meat/beef1.jpg


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts\Cairo-VariableFont_wght.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  